
GET https://localhost:8081/api/v1/herb
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDE0NWJkYjAyM2Y0NDQyNzk3N2FlZGIyZDdhOGM0ODIzMmI4MzhkODExZjk0OTNjZjg3YTk2YmVlYzAwNTgxN2MwMmEzNTNkZmRhMDJmYWUiLCJpYXQiOjE2MzA3MDM0NzksIm5iZiI6MTYzMDcwMzQ3OSwiZXhwIjoxNjYyMjM5NDc5LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.ZV0jxfUJKXtvAypGbloMwNKiLhIWd1WGpbeExDPStmu1I-Q_kipPvunc_PueU-ObVhYO7UPL3CYt2A4YxcAeICprM5cmrQPWZGX2Y82r7iMrwpUgLsjVjFf8TE_wheZeUpy1nN0SDZFmdlfJyhZ_1wVal5SEHoa4JSf8GduXAcEcCrqg_gWtV1WdMMD6Y-cyGfd5qhDg_ILTB_Rrh5_iMyZCgNINISkIz4PTZAeUNY0OUq6v3O_Lr4Wd7RpK69TUHw6I4X_Glwjj5o-Hp94Xuh-iopBApZha71vRh8FgRICU6MOBjmDLSVi8lG4RStWz1iMX6a2ihrybZBmjAWPTZEhNJl9xYKl9TSbPLuzoJD6E7v9UoUT5RdIIHlk0WmecoSRT7W_Z3NzUPsc3dQvUEkJALCr8m_U-yClIAXZXs0ZeTtQ2jCSVDscwkPmxnzRrvjqg1VRfk0RHaMhycTzGG5qY85nceiowiXpuUq5m4_RaQbUDoLvS9YkiCtH4lhCtnb7JM2NtLJlPurgkxt3B87JCgmVt8SpTeQnFS-bwreCxYSz-Qc1S4uwsDXzwKYttDNOt4HbdHByn__zxwYGL_5syrvuHnXwniJVtuTkFE01Pu6iIGVHLuvYsNEUVzOdNQY33Ahh-9x20lTHIwclyhaQLz5rgj1CzxMqpkOD8COY
Accept: application/json

{
    "name":"микроб"
}
###
GET https://localhost:8081/api/v1/herb
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDE0NWJkYjAyM2Y0NDQyNzk3N2FlZGIyZDdhOGM0ODIzMmI4MzhkODExZjk0OTNjZjg3YTk2YmVlYzAwNTgxN2MwMmEzNTNkZmRhMDJmYWUiLCJpYXQiOjE2MzA3MDM0NzksIm5iZiI6MTYzMDcwMzQ3OSwiZXhwIjoxNjYyMjM5NDc5LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.ZV0jxfUJKXtvAypGbloMwNKiLhIWd1WGpbeExDPStmu1I-Q_kipPvunc_PueU-ObVhYO7UPL3CYt2A4YxcAeICprM5cmrQPWZGX2Y82r7iMrwpUgLsjVjFf8TE_wheZeUpy1nN0SDZFmdlfJyhZ_1wVal5SEHoa4JSf8GduXAcEcCrqg_gWtV1WdMMD6Y-cyGfd5qhDg_ILTB_Rrh5_iMyZCgNINISkIz4PTZAeUNY0OUq6v3O_Lr4Wd7RpK69TUHw6I4X_Glwjj5o-Hp94Xuh-iopBApZha71vRh8FgRICU6MOBjmDLSVi8lG4RStWz1iMX6a2ihrybZBmjAWPTZEhNJl9xYKl9TSbPLuzoJD6E7v9UoUT5RdIIHlk0WmecoSRT7W_Z3NzUPsc3dQvUEkJALCr8m_U-yClIAXZXs0ZeTtQ2jCSVDscwkPmxnzRrvjqg1VRfk0RHaMhycTzGG5qY85nceiowiXpuUq5m4_RaQbUDoLvS9YkiCtH4lhCtnb7JM2NtLJlPurgkxt3B87JCgmVt8SpTeQnFS-bwreCxYSz-Qc1S4uwsDXzwKYttDNOt4HbdHByn__zxwYGL_5syrvuHnXwniJVtuTkFE01Pu6iIGVHLuvYsNEUVzOdNQY33Ahh-9x20lTHIwclyhaQLz5rgj1CzxMqpkOD8COY
Accept: application/json

{
  "name":"Брус"
}